version: "3.7"
services:
  gin-server:
    build: ./
    restart: "no"
    command: go run main.go
    container_name: syeong-server
    ports:
      - 80:8080
    volumes:
      - ./logs:/build/logs
  mongodb:
    image: mongo:latest
    restart: "no"
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo/data/db:/data/db
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
